name: Makefile CI

on:
  schedule:
  - cron: "0 5 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: build release
      run: make release
    
    - uses: actions/upload-artifact@v2
      with:
        # NYI get version from version-file
        path: fuzion_language_server_0.3.0.zip
      
    
