name: Makefile CI

on:
  schedule:
  - cron: "15 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: update submodule
      run: git submodule update --init --recursive
    
    - name: build release
      run: make release

    - uses: actions/upload-artifact@v2
      with:
        # NYI get version from version-file
        path: fuzion_language_server_0.3.0.zip


